# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right

# Search form
search: true

# Widgets
widgets:
- about
- category
- tag

# Miscellaneous
google_analytics:
favicon: /favicon.png
avatar:
google_plus:
fb_admins:
fb_app_id:

social:
  twitter: //twitter.com/
  facebook: //www.facebook.com/
  github: //github.com/

aboutme: Your Profile.

about:
  author: true
  avatar: true
  aboutme: true
  description: true
  social: true

common_keywords:
